# 本番環境用 Jellyfin Docker Compose設定
version: '3.8'

services:
  jellyfin:
    container_name: jellyfin_prod
    image: jellyfin/jellyfin:latest
    user: 1000:1000
    environment:
      - JELLYFIN_PublishedServerUrl=http://localhost:8096
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes:
      - ${JELLYFIN_CONFIG_PATH}:/config
      - ${JELLYFIN_CACHE_PATH}:/cache
      - ${JELLYFIN_MEDIA_PATH}:/media:ro
      - ${DATA_ROOT}/temp:/temp
    ports:
      - "8096:8096"
      - "8920:8920"  # HTTPS
      - "7359:7359/udp"  # 自動検出用
      - "1900:1900/udp"  # DLNA
    restart: unless-stopped
    networks:
      - jellyfin
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  jellyfin:
    name: jellyfin-prod
    driver: bridge

volumes:
  jellyfin-config:
    driver: local
  jellyfin-cache:
    driver: local
