version: '3.8'

services:
  immich:
    image: ghcr.io/immich-app/immich:latest
    container_name: immich
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/immich
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret
      - STORAGE_PROVIDER=local
      - STORAGE_PATH=/data/immich
    volumes:
      - immich_data:/data/immich
    depends_on:
      - db
      - redis

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - JELLYFIN_PublishedServerUrl=http://your_jellyfin_url
      - JELLYFIN_Username=your_username
      - JELLYFIN_Password=your_password
    volumes:
      - jellyfin_data:/data/jellyfin
    ports:
      - "8096:8096"
      - "8920:8920"

  db:
    image: postgres:latest
    container_name: immich_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=immich
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: immich_redis
    volumes:
      - redis_data:/data

volumes:
  immich_data:
  jellyfin_data:
  db_data:
  redis_data: